# Generated by Django 3.1.1 on 2020-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='max_level',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='level',
            name='min_level',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='level',
            name='routes',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
