# Generated by Django 3.1.1 on 2020-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0003_auto_20200914_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='max_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='min_level',
            field=models.IntegerField(null=True),
        ),
    ]
