# Generated by Django 3.1.1 on 2020-09-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0004_auto_20200914_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='max_level',
        ),
    ]
